server:
  port: 8761

eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false

spring:
  application:
    name: eureka-server
  cloud:
    config:
      uri: http://config-server:8888
      profile: dev
      label: main    

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
